### PR TITLE
Add Guardian image from Legend of Zelda

### PR DESCRIPTION
**Pull request by hugomd**

### CODE REVIEW

**Comment by hugomd** [comment]
@kochie pls

**Comment by lorderikir** [comment]
WE NEED THISS!!!!!!!!

@kochie WHY ARE U IGNORING THIS PR

**Comment by lorderikir** [comment]
Finally. 
celebrate

**Comment by hugomd** [comment]
Thanks for merging this in @kochie 🙏

**Comment by kochie** [comment]
I didn't see it. soz

**Pull request merged**
